name: CodeFlash

on:
  pull_request:
  workflow_dispatch:

jobs:
  optimize:
    name: Optimize new code in this PR
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_AI_KEY: ${{ secrets.CODEFLASH_AI_KEY }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install 'https://www.dropbox.com/scl/fi/aptmn35lr6e0ntobia8v1/codeflash-0.4.3-py3-none-any.whl?rlkey=ce6fwzpdtoi1sdhxygm06l9sj&dl=1'
      - name: Run CodeFlash to optimize code
        id: optimize_code
        run: |
          poetry env use python 
          poetry run codeflash

