name: CodeFlash

on:
  pull_request:
  workflow_dispatch:

jobs:
  optimize:
    name: Optimize new code in this PR
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_AI_KEY: ${{ secrets.CODEFLASH_AI_KEY }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'https://www.dropbox.com/scl/fi/xuig76b0xcdxlgomy8r7n/codeflash-oni-py3-none-any.whl?rlkey=g9p4cm60p4l9g1wqysrrtlrwm&dl=1'
      - name: Run CodeFlash to optimize code
        id: optimize_code
        run: |
          PYTHONPATH=`pwd` codeflash

